name       : consul
version    : 1.16.1
release    : 7
source     :
    - https://github.com/hashicorp/consul/archive/refs/tags/v1.16.1.tar.gz : 9fec1683131ff122a43512f265131729e20212e26353d017805c5566dfec2333
homepage   : https://www.consul.io/
license    : MPL-2.0
component  : virt
summary    : A tool for service discovery, monitoring and configuration
description: |
    Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    %make tools
build      : |
    %make dev
install    : |
    install -Dm00755 bin/consul $installdir/usr/bin/consul
