name       : consul
version    : 1.10.4
release    : 5
source     :
    - https://github.com/hashicorp/consul/archive/refs/tags/v1.10.4.tar.gz : 6e3da1fb589586af4d68b2e924ccdb9f4aad644826aae452c31744c658eb66e4
license    : MPL-2.0
component  : virt
summary    : Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure
description: |
    Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.
networking : yes
builddeps  :
    - git
    - golang
setup      : |
    %make tools
build      : |
    %make dev
install    : |
    install -Dm00755 bin/consul $installdir/usr/bin/consul
